Fix problem within the dependency loader causing a TypeError
We got the following error when loading the email account view through the accounts
application:

TypeError: undefined is not an object (evaluating 'c.replace')

Signed-off-by: Simon Busch <morphis@gravedo.de>